name: Update Weather Forecast

on:
  #schedule:
  #  - cron: "*/30 * * * *"  # Cada 30 minutos
  workflow_dispatch:        # Permite ejecución manual

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3
      with:
        token: ${{ secrets.GH_PAT }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install requests

    - name: Run weather update script
      env:
        OWM_API_KEY: ${{ secrets.OWM_API_KEY }}
      run: |
        sed -i "s/YOUR_API_KEY/$OWM_API_KEY/" update_weather.py
        python update_weather.py

    - name: Commit and push changes
      run: |
        git config user.name "github-actions"
        git config user.email "github-actions@github.com"
        git add weather_forecast.html
        git commit -m "Update weather forecast [auto]" || echo "No changes to commit"
        git push
